Repository eclipse-lsp4mp/lsp4mp, pull requests merged in 2020-09, with the labels that each got.

#47 Fix missing unit in Gauge metrics snippet
  microprofile.ls/org.eclipse.lsp4mp.ls/src/main/resources/org/eclipse/lsp4mp/snippets/mp-metrics.json
Labels: snippets

#67 Fix symbols NPE in microprofile-config
  microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/services/MicroProfileSymbolsProvider.java
  microprofile.ls/org.eclipse.lsp4mp.ls/src/test/java/org/eclipse/lsp4mp/services/ApplicationPropertiesSymbolsTest.java
Labels: bug

#43 Add support for MP GraphQL properties
  microprofile.jdt/org.eclipse.lsp4mp.jdt.core/plugin.xml
  microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/graphql/MicroProfileGraphQLConstants.java
  microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/graphql/properties/MicroProfileGraphQLProvider.java
  microprofile.jdt/org.eclipse.lsp4mp.jdt.core/static-properties/mp-graphql-metadata.json
  microprofile.jdt/org.eclipse.lsp4mp.jdt.test/projects/maven/microprofile-graphql/.classpath
  microprofile.jdt/org.eclipse.lsp4mp.jdt.test/projects/maven/microprofile-graphql/.project
  microprofile.jdt/org.eclipse.lsp4mp.jdt.test/projects/maven/microprofile-graphql/pom.xml
  microprofile.jdt/org.eclipse.lsp4mp.jdt.test/projects/maven/microprofile-graphql/src/main/java/io/openliberty/graphql/sample/Conditions.java
  microprofile.jdt/org.eclipse.lsp4mp.jdt.test/projects/maven/microprofile-graphql/src/main/java/io/openliberty/graphql/sample/PrecipType.java
  microprofile.jdt/org.eclipse.lsp4mp.jdt.test/projects/maven/microprofile-graphql/src/main/java/io/openliberty/graphql/sample/UnknownLocationException.java
  microprofile.jdt/org.eclipse.lsp4mp.jdt.test/projects/maven/microprofile-graphql/src/main/java/io/openliberty/graphql/sample/WeatherService.java
  microprofile.jdt/org.eclipse.lsp4mp.jdt.test/projects/maven/microprofile-graphql/src/main/java/io/openliberty/graphql/sample/client/JaxrsResource.java
  microprofile.jdt/org.eclipse.lsp4mp.jdt.test/projects/maven/microprofile-graphql/src/main/java/io/openliberty/graphql/sample/client/TempAndPrecip.java
  microprofile.jdt/org.eclipse.lsp4mp.jdt.test/projects/maven/microprofile-graphql/src/main/java/io/openliberty/graphql/sample/client/WeatherApi.java
  microprofile.jdt/org.eclipse.lsp4mp.jdt.test/projects/maven/microprofile-graphql/src/main/resources/META-INF/microprofile-config.properties
  microprofile.jdt/org.eclipse.lsp4mp.jdt.test/src/main/java/org/eclipse/lsp4mp/jdt/core/BasePropertiesManagerTest.java
  microprofile.jdt/org.eclipse.lsp4mp.jdt.test/src/main/java/org/eclipse/lsp4mp/jdt/core/graphql/MicroProfileGraphQLTest.java
Labels: requires CQ

#72 List vscode-microprofile under clients
  README.md
Labels: documentation
