Repository eclipse-lsp4mp/lsp4mp, pull requests merged in 2024-10, with the labels that each got.

#462 fix : prevent from empty name symbol
  microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/services/properties/PropertiesFileSymbolsProvider.java
  microprofile.ls/org.eclipse.lsp4mp.ls/src/test/java/org/eclipse/lsp4mp/services/properties/PropertiesFileSymbolsTest.java
Labels: bug

#464 fix: split register completion options for Java / Properties
  microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/MicroProfileLanguageIds.java
  microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/settings/capabilities/MicroProfileCapabilityManager.java
  microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/settings/capabilities/ServerCapabilitiesConstants.java
  microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/settings/capabilities/ServerCapabilitiesInitializer.java
  microprofile.ls/org.eclipse.lsp4mp.ls/src/test/java/org/eclipse/lsp4mp/settings/capabilities/MicroProfileCapabilitiesTest.java
Labels: bug

#465 fix: prevent from duplicate properties
  microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/core/AbstractAnnotationTypeReferencePropertiesProvider.java
  microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/core/AbstractPropertiesProvider.java
  microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/core/AbstractTypeDeclarationPropertiesProvider.java
Labels: bug

#467 REST endpoint codelens is not resolving a `public static final` parameter
  microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/core/jaxrs/JaxRsContext.java
  microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/core/utils/AnnotationUtils.java
  microprofile.jdt/org.eclipse.lsp4mp.jdt.test/projects/maven/hibernate-orm-resteasy-yaml/src/main/java/org/acme/hibernate/orm/FruitResource.java
  microprofile.jdt/org.eclipse.lsp4mp.jdt.test/projects/maven/hibernate-orm-resteasy/src/main/java/org/acme/hibernate/orm/FruitResource.java
  microprofile.jdt/org.eclipse.lsp4mp.jdt.test/src/main/java/org/eclipse/lsp4mp/jdt/core/jaxrs/java/JaxRsCodeLensTest.java
Labels: bug, java-files, codelens

#468 Enum support in AnnotationUtils
  microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/core/utils/AnnotationUtils.java
Labels: bug

#472 Update date to 22 october
  CHANGELOG.md
Labels: documentation

#474 Certain test suites should avoid re-importing projects if not necessary.
  microprofile.jdt/org.eclipse.lsp4mp.jdt.test/src/main/java/org/eclipse/lsp4mp/jdt/core/config/java/MicroProfileConfigJavaHoverTest.java
  microprofile.jdt/org.eclipse.lsp4mp.jdt.test/src/main/java/org/eclipse/lsp4mp/jdt/core/snippets/JavaFileCursorContextTest.java
Labels: build
